from django.test import TestCase

# Create your tests here.
# reading/dummy_data.py
DUMMY_QUESTIONS = [
    {
        "id": 1,
        "question_type": "Multiple Choice Questions",
        "level": "easy",
        "passage": "The Great Barrier Reef is the world’s largest coral reef system, stretching over 2,300 kilometers. It is home to thousands of species of marine life and is a UNESCO World Heritage Site.",
        "question_stem": "What is the Great Barrier Reef?",
        "options": [
            {"letter": "A", "text": "A desert in Australia", "is_correct": False},
            {"letter": "B", "text": "A coral reef system", "is_correct": True},
            {"letter": "C", "text": "A mountain range", "is_correct": False},
            {"letter": "D", "text": "A tropical rainforest", "is_correct": False},
        ],
        "explanation": "The passage clearly states that the Great Barrier Reef is the world’s largest coral reef system.",
        "status": "notStarted",
        "score": None,
    },
    {
        "id": 2,
        "question_type": "True/False/Not Given",
        "level": "medium",
        "passage": "Urban farming is growing in popularity in cities worldwide. It involves cultivating crops and raising animals in urban areas, often on rooftops or vacant lots. Studies show it can reduce food miles.",
        "question_stem": "Urban farming always takes place on rooftops.",
        "options": [
            {"letter": "A", "text": "True", "is_correct": False},
            {"letter": "B", "text": "False", "is_correct": True},
            {"letter": "C", "text": "Not Given", "is_correct": False},
        ],
        "explanation": "The passage mentions rooftops as one location but also includes vacant lots, so it’s not always on rooftops.",
        "status": "inProgress",
        "score": None,
    },
    {
        "id": 3,
        "question_type": "Matching Headings",
        "level": "hard",
        "passage": "Paragraph 1: Renewable energy sources like solar and wind are becoming more cost-effective. Paragraph 2: However, their intermittent nature poses challenges for grid stability.",
        "question_stem": "Match the heading to Paragraph 1.",
        "options": [
            {"letter": "A", "text": "Challenges of Renewable Energy", "is_correct": False},
            {"letter": "B", "text": "Cost-Effectiveness of Renewables", "is_correct": True},
            {"letter": "C", "text": "Grid Stability Issues", "is_correct": False},
            {"letter": "D", "text": "Non-Renewable Energy Sources", "is_correct": False},
        ],
        "explanation": "Paragraph 1 discusses the cost-effectiveness of renewable energy, matching heading B.",
        "status": "completed",
        "score": 100,
    },
    {
        "id": 4,
        "question_type": "Sentence Completion",
        "level": "medium",
        "passage": "Electric vehicles (EVs) are powered by batteries and produce zero tailpipe emissions. They are increasingly popular due to environmental concerns.",
        "question_stem": "Electric vehicles produce ______ tailpipe emissions.",
        "options": [
            {"letter": "A", "text": "high", "is_correct": False},
            {"letter": "B", "text": "zero", "is_correct": True},
            {"letter": "C", "text": "moderate", "is_correct": False},
            {"letter": "D", "text": "unknown", "is_correct": False},
        ],
        "explanation": "The passage states that EVs produce zero tailpipe emissions.",
        "status": "notStarted",
        "score": None,
    },
    {
        "id": 5,
        "question_type": "Matching Information",
        "level": "hard",
        "passage": "Paragraph 1: Artificial intelligence is transforming healthcare through diagnostics. Paragraph 2: It also raises ethical concerns about data privacy.",
        "question_stem": "Which paragraph mentions ethical concerns?",
        "options": [
            {"letter": "A", "text": "Paragraph 1", "is_correct": False},
            {"letter": "B", "text": "Paragraph 2", "is_correct": True},
        ],
        "explanation": "Paragraph 2 explicitly mentions ethical concerns about data privacy.",
        "status": "completed",
        "score": 80,
    },
    {
        "id": 6,
        "question_type": "Multiple Choice Questions",
        "level": "easy",
        "passage": "The Amazon Rainforest is known as the 'lungs of the Earth' because it produces a significant amount of the world's oxygen.",
        "question_stem": "Why is the Amazon Rainforest called the 'lungs of the Earth'?",
        "options": [
            {"letter": "A", "text": "It absorbs carbon dioxide", "is_correct": False},
            {"letter": "B", "text": "It produces oxygen", "is_correct": True},
            {"letter": "C", "text": "It stores water", "is_correct": False},
            {"letter": "D", "text": "It prevents flooding", "is_correct": False},
        ],
        "explanation": "The passage states that the Amazon produces oxygen, earning it the nickname.",
        "status": "notStarted",
        "score": None,
    },
    {
        "id": 7,
        "question_type": "True/False/Not Given",
        "level": "medium",
        "passage": "Recycling programs in many cities have reduced landfill waste. However, not all materials can be recycled easily.",
        "question_stem": "All materials can be recycled easily.",
        "options": [
            {"letter": "A", "text": "True", "is_correct": False},
            {"letter": "B", "text": "False", "is_correct": True},
            {"letter": "C", "text": "Not Given", "is_correct": False},
        ],
        "explanation": "The passage states that not all materials can be recycled easily, so the statement is false.",
        "status": "inProgress",
        "score": None,
    },
    {
        "id": 8,
        "question_type": "Matching Headings",
        "level": "hard",
        "passage": "Paragraph 1: Climate change is causing rising sea levels. Paragraph 2: Mitigation efforts include reducing carbon emissions.",
        "question_stem": "Match the heading to Paragraph 2.",
        "options": [
            {"letter": "A", "text": "Effects of Climate Change", "is_correct": False},
            {"letter": "B", "text": "Mitigation Strategies", "is_correct": True},
            {"letter": "C", "text": "Sea Level Rise", "is_correct": False},
        ],
        "explanation": "Paragraph 2 discusses mitigation efforts, matching heading B.",
        "status": "completed",
        "score": 90,
    },
    {
        "id": 9,
        "question_type": "Short-Answer Questions",
        "level": "easy",
        "passage": "The Eiffel Tower in Paris was constructed for the 1889 World’s Fair.",
        "question_stem": "For what event was the Eiffel Tower built?",
        "options": [
            {"letter": "A", "text": "1889 World’s Fair", "is_correct": True},
            {"letter": "B", "text": "1900 Olympics", "is_correct": False},
            {"letter": "C", "text": "1870 Festival", "is_correct": False},
        ],
        "explanation": "The passage states the Eiffel Tower was built for the 1889 World’s Fair.",
        "status": "notStarted",
        "score": None,
    },
    {
        "id": 10,
        "question_type": "Summary Completion",
        "level": "medium",
        "passage": "Telecommuting allows employees to work from home, reducing commuting time and costs. It also promotes work-life balance.",
        "question_stem": "Telecommuting reduces ______ and promotes work-life balance.",
        "options": [
            {"letter": "A", "text": "commuting time", "is_correct": True},
            {"letter": "B", "text": "office space", "is_correct": False},
            {"letter": "C", "text": "work hours", "is_correct": False},
        ],
        "explanation": "The passage mentions that telecommuting reduces commuting time and promotes work-life balance.",
        "status": "notStarted",
        "score": None,
    },
]